# Simple workflow for deploying static content to GitHub Pages
name: Github Pages Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  cart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd cart
      - run: npm ci
      - run: npm test
      - run: npm run build

  products:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd products
      - run: npm ci
      - run: npm test
      - run: npm run build

  container:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: (cd container; npm ci)
      - run: (cd container; npm run build)

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./container/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
